### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by J-Christophe** [MizarWeb/ipymizar#1]
It seems some files are missing **ValueError: missing files: ['ipymizar/nbextension/index.js', 'ipymizar/labextension/package.json']**

```
malapert@heulet-HP-ZBook-15-G4:~/ipymizar$ pip install .

Processing /home/malapert/ipymizar
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: ipywidgets<8,>=7.6.0 in /home/malapert/.local/lib/python3.8/site-packages (from ipymizar==0.1.0) (7.6.3)
Collecting traittypes<3,>=0.2.1
  Downloading traittypes-0.2.1-py2.py3-none-any.whl (8.6 kB)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/lib/python3/dist-packages (from ipywidgets<8,>=7.6.0->ipymizar==0.1.0) (5.2.0)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in /usr/lib/python3/dist-packages (from ipywidgets<8,>=7.6.0->ipymizar==0.1.0) (7.13.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /home/malapert/.local/lib/python3.8/site-packages (from ipywidgets<8,>=7.6.0->ipymizar==0.1.0) (3.5.1)
Requirement already satisfied: traitlets>=4.3.1 in /usr/lib/python3/dist-packages (from ipywidgets<8,>=7.6.0->ipymizar==0.1.0) (4.3.3)
Requirement already satisfied: jupyterlab-widgets>=1.0.0; python_version >= "3.6" in /home/malapert/.local/lib/python3.8/site-packages (from ipywidgets<8,>=7.6.0->ipymizar==0.1.0) (1.0.0)
Requirement already satisfied: nbformat>=4.2.0 in /usr/lib/python3/dist-packages (from ipywidgets<8,>=7.6.0->ipymizar==0.1.0) (5.0.4)
Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets<8,>=7.6.0->ipymizar==0.1.0) (4.6.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/lib/python3/dist-packages (from widgetsnbextension~=3.5.0->ipywidgets<8,>=7.6.0->ipymizar==0.1.0) (6.0.3)
Building wheels for collected packages: ipymizar
  Building wheel for ipymizar (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /tmp/tmp46if_g45 build_wheel /tmp/tmpbj2z51pl
       cwd: /tmp/pip-req-build-dkr9gwqi
  Complete output (39 lines):
  running bdist_wheel
  running jsdeps
  `yarn` unavailable.  If you're running this command using sudo, make sure `yarn` is available to sudo
  Traceback (most recent call last):
    File "/tmp/tmp46if_g45", line 280, in <module>
      main()
    File "/tmp/tmp46if_g45", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmp46if_g45", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-m0pvbe52/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-m0pvbe52/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-m0pvbe52/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 81, in <module>
      setup(**setup_args)
    File "/tmp/pip-build-env-m0pvbe52/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-m0pvbe52/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 503, in run
      [self.run_command(cmd) for cmd in cmds]
    File "/tmp/pip-build-env-m0pvbe52/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 503, in <listcomp>
      [self.run_command(cmd) for cmd in cmds]
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-m0pvbe52/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 274, in run
      c.run()
    File "/tmp/pip-build-env-m0pvbe52/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 401, in run
      raise ValueError(('missing files: %s' % missing))
  ValueError: missing files: ['ipymizar/nbextension/index.js', 'ipymizar/labextension/package.json']
  ----------------------------------------
  ERROR: Failed building wheel for ipymizar
Failed to build ipymizar
ERROR: Could not build wheels for ipymizar which use PEP 517 and cannot be installed directly
```

**Comment by serut** [comment]
Hello,
You do not have yarn installed : `  yarn unavailable.  If you're running this command using sudo, make sure yarn is available to sudo`

**Comment by J-Christophe** [comment]
Thanks, it works
